# Generated by Django 4.1.3 on 2022-11-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0002_remove_author_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
